export const PL_MATCHES_REQUEST = 'PL_MATCHES_REQUEST'
export const PL_MATCHES_SUCCESS = 'PL_MATCHES_SUCCESS'
export const PL_MATCHES_FAILURE = 'PL_MATCHES_FAILURE'

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST'
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'

export const SET_YEAR = 'SET_YEAR'
export const GET_MATCHES = 'GET_MATCHES'